main: me.deltarays.discordconsole.DiscordConsole
name: DiscordConsole
api-version: 1.16
version: 1.4.0
load: STARTUP
author: DeltaRays
description: Connect your minecraft console to a discord channel!
softdepend:
  - PlaceholderAPI
commands:
  discordconsole:
    aliases:
      - discordc
    description: The plugin's main command
    usage: discordconsole [<reload|updatecheck>]