main: tk.deltarays.discordconsole.DiscordConsole
name: DiscordConsole
version: 1.3.0
author: DeltaRays
description: Connect your minecraft console to a discord channel!
softdepend:
  - PlaceholderAPI
commands:
  discordconsole:
    aliases:
      - discordc
    description: The plugin's main command
    usage: discordconsole [<reload|updatecheck>]